version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      time: '03:00'
      timezone: 'Europe/Helsinki'
    labels:
      - 'dependencies'
      - 'dependabot'
    rebase-strategy: 'disabled'
    open-pull-requests-limit: 5
