AWSTemplateFormatVersion: 2010-09-09
Description: 'Lambda@Edge for adding secure HTTP headers to CloudFront responses'
Transform: AWS::Serverless-2016-10-31

Parameters:
  app:
    Type: String
    Description: Name of the application (e.g. my-app)
  stage:
    Type: String
    Description: Name of the stage (e.g. dev)

Resources:
  LambdaEdgeFunctionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: '/'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: 'AllowLambdaServiceToAssumeRole'
            Effect: 'Allow'
            Action:
              - 'sts:AssumeRole'
            Principal:
              Service:
                - 'lambda.amazonaws.com'
                - 'edgelambda.amazonaws.com'

  HttpSecureHeadersAppenderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${stage}-${app}-http-secure-headers-appender
      Description: 'Lambda for appending secure HTTP headers to CloudFront responses'
      Runtime: nodejs14.x
      CodeUri: dist
      Handler: index.handler
      Timeout: 1
      AutoPublishAlias: live
      Role: !GetAtt LambdaEdgeFunctionRole.Arn
    Tags:
      - Key: 'application'
        Vale: '${app}'
      - Key: 'stage'
        Value: '${stage}'

Outputs:
  VersionArn:
    Description: 'ARN for http secure headers Lambda@edge function'
    Value: !Ref HttpSecureHeadersAppenderFunction.Version
    Export:
      Name: !Sub 'HttpSecureHeadersAppenderFunctionArn'
